/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'

const ResourceAllocationLazyRouteImport = createFileRoute(
  '/resource-allocation',
)()
const IndexLazyRouteImport = createFileRoute('/')()

const ResourceAllocationLazyRoute = ResourceAllocationLazyRouteImport.update({
  id: '/resource-allocation',
  path: '/resource-allocation',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/resource-allocation.lazy').then((d) => d.Route),
)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/demo.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/demo': typeof DemoRoute
  '/resource-allocation': typeof ResourceAllocationLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/demo': typeof DemoRoute
  '/resource-allocation': typeof ResourceAllocationLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/demo': typeof DemoRoute
  '/resource-allocation': typeof ResourceAllocationLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/resource-allocation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/resource-allocation'
  id: '__root__' | '/' | '/demo' | '/resource-allocation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DemoRoute: typeof DemoRoute
  ResourceAllocationLazyRoute: typeof ResourceAllocationLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resource-allocation': {
      id: '/resource-allocation'
      path: '/resource-allocation'
      fullPath: '/resource-allocation'
      preLoaderRoute: typeof ResourceAllocationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DemoRoute: DemoRoute,
  ResourceAllocationLazyRoute: ResourceAllocationLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
