/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as Tenant_formRouteImport } from './routes/tenant_form'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as Request_formRouteImport } from './routes/request_form'
import { Route as DemoRouteImport } from './routes/demo'

const ResourceAllocationLazyRouteImport = createFileRoute(
  '/resource-allocation',
)()
const IndexLazyRouteImport = createFileRoute('/')()

const ResourceAllocationLazyRoute = ResourceAllocationLazyRouteImport.update({
  id: '/resource-allocation',
  path: '/resource-allocation',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/resource-allocation.lazy').then((d) => d.Route),
)
const Tenant_formRoute = Tenant_formRouteImport.update({
  id: '/tenant_form',
  path: '/tenant_form',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const Request_formRoute = Request_formRouteImport.update({
  id: '/request_form',
  path: '/request_form',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/demo.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/demo': typeof DemoRoute
  '/request_form': typeof Request_formRoute
  '/tenant': typeof TenantRoute
  '/tenant_form': typeof Tenant_formRoute
  '/resource-allocation': typeof ResourceAllocationLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/demo': typeof DemoRoute
  '/request_form': typeof Request_formRoute
  '/tenant': typeof TenantRoute
  '/tenant_form': typeof Tenant_formRoute
  '/resource-allocation': typeof ResourceAllocationLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/demo': typeof DemoRoute
  '/request_form': typeof Request_formRoute
  '/tenant': typeof TenantRoute
  '/tenant_form': typeof Tenant_formRoute
  '/resource-allocation': typeof ResourceAllocationLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/request_form'
    | '/tenant'
    | '/tenant_form'
    | '/resource-allocation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/request_form'
    | '/tenant'
    | '/tenant_form'
    | '/resource-allocation'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/request_form'
    | '/tenant'
    | '/tenant_form'
    | '/resource-allocation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DemoRoute: typeof DemoRoute
  Request_formRoute: typeof Request_formRoute
  TenantRoute: typeof TenantRoute
  Tenant_formRoute: typeof Tenant_formRoute
  ResourceAllocationLazyRoute: typeof ResourceAllocationLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resource-allocation': {
      id: '/resource-allocation'
      path: '/resource-allocation'
      fullPath: '/resource-allocation'
      preLoaderRoute: typeof ResourceAllocationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant_form': {
      id: '/tenant_form'
      path: '/tenant_form'
      fullPath: '/tenant_form'
      preLoaderRoute: typeof Tenant_formRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request_form': {
      id: '/request_form'
      path: '/request_form'
      fullPath: '/request_form'
      preLoaderRoute: typeof Request_formRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DemoRoute: DemoRoute,
  Request_formRoute: Request_formRoute,
  TenantRoute: TenantRoute,
  Tenant_formRoute: Tenant_formRoute,
  ResourceAllocationLazyRoute: ResourceAllocationLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
